### ISSUE TITLE
Problemas para generar un RPCGen en la segunda parte del programa

### ISSUE THREAD

**Issue by SeanBurger72** [Innova4DLab/RMI#1]
Aquí esta mi código me marca error pero no entiendo el porque requiero apoyo para terminar la parte 2 de la práctica

struct intpair {
int a;
int b;
};
program AgregaBusca_PROG {
version AgregaBUsca_VERS {
time_t t = time(NULL);
struct tm tm = *localtime(&t);

printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);

time_t t = time(NULL);
struct tm tm = *localtime(&t);

printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
#include <stdlib.h>
 #include <string.h>

 char buff[1000];
 char *s;

 s = strstr(buff, "hassasin");      // search for string "hassasin" in buff
 if (s != NULL)                     // if succesfull then s now points at "hassasin"
 {
     printf("Found string at index = %d\n", s - buff);
 }                                  // index of "hassasin" in buff can be found by pointer subtraction
 else
 {
     printf("String not found\n");  // `strstr` returns NULL if search string not found
 }

}}

**Comment by FranciscoGutierrez** [comment]
¿Hola, podrías poner el error que aparece en la consola?

Para escribir en un archivo puedes usar el siguiente código: 

``` c
private void index(){
MessageBox.Show("hello world");
}

FILE *f = fopen("file.txt", "w");
if (f == NULL) {
    printf("Error opening file!\n");
    exit(1);
}

/* print some text */
const char *text = "Write this to the file";
fprintf(f, "Some text: %s\n", text);
fclose(f);
```

**Comment by FranciscoGutierrez** [comment]
Éste es el repositorio de RMI xD
